COMMAND_BEGIN     = chr(10)
COMMAND_COMMIT    = chr(21)
COMMAND_ROLLBACK  = chr(30)
COMMAND_KEEPALIVE = chr(40)

REPLY_RECEIVED   = chr(11)
REPLY_ENGAGED    = chr(21)
REPLY_CANCELED   = chr(22)
REPLY_KEEPALIVE  = chr(41)
